### ISSUE TITLE
Joining a scoping Session: Unable to join a scoping Session

### ISSUE THREAD

**Issue by Wholloran** [openforge/junto-scope#100]
When hosting a session from either Android or iOS, other participants are unable to join the session. When entering the session URL from either an iOS device or Android you are taken to a screen with a loading spinner but it never goes away, and you are never asked for the session access code.

iPhone X, iPhone 6+, Google Pixel, Sony Xperia

**Comment by Fdom92** [comment]
@Wholloran i created a session logged in on the browser with one account (google) and then on my device joined it and could go scoping tasks.

Also i was prompted to enter the access code and then go to the scoping flow.

**Comment by Wholloran** [comment]
I am able to join a scoping session, At the time of writing the ticket, I was using the whole URL rather than the last 4 characters of it. Closing the ticket.
