### ISSUE TITLE
Dashboard: arrow on history Card

### ISSUE THREAD

**Issue by Wholloran** [openforge/junto-scope#102]
Seeing as the arrow on the history card currently does expand and collapse the history card, and after review with Rachel about if that feature would even be wanted we will just remove the Arrow.

**Comment by PaulPaulDevelops** [comment]
Hey! I updated this per our conversation in the branch `history-header`. I'm going to run it by Rachel before creating a PR or merging into `feature/ionic-3`

**Comment by Wholloran** [comment]
looks as expected per our conversation, closing ticket
