### ISSUE TITLE
Login(): Redirect after Facebook authentication

### ISSUE THREAD

**Issue by PaulPaulDevelops** [openforge/junto-scope#104]
On an Android device, the user is not redirected after successful authentication. @Fdom92 and I tried to debug this, and it seems that Facebook and Firebase did successfully authenticate, but does not transition to the dashboard.

**Comment by PaulPaulDevelops** [comment]
This is the same issue as #105 with the response being slow from Firebase so we aren't navigating the user to the next screen as the result.
The same comment from #105 applies to this issue.

I think it might be best to contact someone from firebase about this issue because it is unusually slow. I authorized Facebook, left my device on the table for a few minutes, saw that I navigated to the dashboard, and looked on the firebase console to verify that the user was successfully registered. 
When I authorized Facebook I checked in the first few seconds to see if the user showed up in the firebase console and they did not.

**Comment by Wholloran** [comment]
The Redirect is now working so I'm closing the ticket. Note this is still very slow.
