### ISSUE TITLE
Authentication(): Add Privacy Policy and Terms of Sevice

### ISSUE THREAD

**Issue by PaulPaulDevelops** [openforge/junto-scope#106]
Remove the current setup pages for this content as it is now hosted on the following links: 
tos.juntoscope.com
pp.juntoscope.com

**Comment by PaulPaulDevelops** [comment]
@Wholloran I added this functionality within the most recent build. Please test and let me know if the links open up properly.

**Comment by PaulPaulDevelops** [comment]
The links I posted above are not links within the juntoscope website. Is this information going to be stored in the application, or link to an external link?

**Comment by Wholloran** [comment]
ToS and PP are working as expected on both iOS and Andriod, closing ticket
