### ISSUE TITLE
Scoping Session: Vote count + Flow progression

### ISSUE THREAD

**Issue by Wholloran** [openforge/junto-scope#131]
Ok, I was able to steady replicate the issue and tie two of the issues together. I will break down each piece and then explain how they are working together.

Vote Count:
When a new session is started and you have your devices join (this instance we will use 4 devices) as the first device joins it will be given the vote count of 0/2(it already knows the moderator will be in the session), the second phone to join will be 0/3 ext.

Steps to recreate:
1.start a new session and generate URL and access code
2. enter URL on phones
3. enter the access code on phones and have them join one by one
the vote counts will be 0/2 0/3 ext.

Flow Progression: 
There will be times when the devices will not navigate to the waiting screen and will sit on the vote submission screens. I was able to confirm the vote is submitting because if you changed the vote it would update on the devices screens that did progress to the waiting screen

How it ties together:
When you go through and start submitting votes one the devices, if the device that has the lower vote count (0/2) doesn't vote first, its counter will move to 2/2 after two other phones submit there vote, pushing it to the waiting screen even though this specific device hasn't voted. Since that device hasn't voted the device(s) with the full vote count 3/4 will be stuck there because one of the devices hasn't voted.

Steps to Recreate:
1. Start a new session and generate URL and access code
2. Enter URL on phones
3. Enter the access code on phones and have them join one by one
4. have the phone with a 0/4 & 0/3 vote count submit there vote
5. after those two devices submit there vote the 0/2 device (the first to join the session) will be pushed to the waiting screen without voting
6.the 3/4 vote counts phone will now not be able to continue forward
7. if you change and resubmit the vote it will change on the other device

**Comment by Wholloran** [comment]
Another small thing I noticed is that once a task scope is picked by the moderator and you are given a brief results screen with that number they selected, the number that was selected is not showing on the devices with the incorrect vote count. (the box will just be blank)

**Comment by daftclaud** [comment]
39bb7905b3810caf19a0b9a1f1a408a6f1b6a547

**Comment by daftclaud** [comment]
#141

**Comment by Wholloran** [comment]
The vote counters are now functioning correctly and the scoping session is flowing correctly. Closing ticket.
