### ISSUE TITLE
Content for FAQ

### ISSUE THREAD

**Issue by PaulPaulDevelops** [openforge/junto-scope#38]
We need the copy of the FAQ information that will display within settings. The logic to pull this and display it from firebase is in place.

**Comment by Wholloran** [comment]
Need @jedihacks  to provide the language for the FAQs. Scope of 1 Hour to put provided language into Firebase database.

**Comment by PaulPaulDevelops** [comment]
The amount of content will dictate the style of the page if it will live within the settings or link out to a separate page with content. Currently, the frontend is implemented as per the design so this will be a minor change.

Please update once the content is available.

**Comment by PaulPaulDevelops** [comment]
Closing this as is a feature that has not been fully flushed out and not an issue.
