### ISSUE TITLE
Unit tests are not getting executed

### ISSUE THREAD

**Issue by mohammad-alfatih** [openforge/junto-scope#42]
**Working Environment**
- node 10.1.0
- `"@angular/cli": "6.0.0"`

**Steps to reproduce**
- Go to the branch `unit-tests`.
- Run the command `rm -rf node-modules; npm i`
- After all modules have re-installed, run `ng test`

The following error pops up `Executed 0 of 0 ERROR`

**Comment by Fdom92** [comment]
Seems to be a problem with `@angular-devkit/build-angular` so just update that one to `^0.6.8` and should works
