### ISSUE TITLE
v3 - Capitalize the connectionData type

### ISSUE THREAD

**Issue by PaulPaulDevelops** [openforge/junto-scope#52]
We should manipulate the type to start with a capital letter in the front-end because it is something that is included in header titles and information. So the change would manipulate 'teamwork' to 'Teamwork' .

I think it would look better because it is usually next to the company name. And we are using Teamwork as a third party service / API so we should use the proper brand name style.

**Comment by nbey** [comment]
https://github.com/openforge/junto-scope/pull/51 resolves this in the session history, and project selection screens.

**Comment by Fdom92** [comment]
Already fixed and merged
