### ISSUE TITLE
Join Scoping Session

### ISSUE THREAD

**Issue by nbey** [openforge/junto-scope#54]
When attempting to join a scoping session, if you enter an invalid access code, or the code has expired, the error shows accordingly. However, if you go back to the dashboard, and try to enter a new session link, the previous error still shows.

- [x] Destroy error state when navigating back to the dashboard
- [ ] Consider showing invalid access link, before navigating to the access code screen (?)

**Comment by PaulPaulDevelops** [comment]
@Wholloran could you verify this above when you QA? If it is still applicable please keep it open, if not please close the issue. Thanks.

**Comment by Fdom92** [comment]
@PaulPaulDevelops i checked this and seems to still showing the error after the first time, going to work on this.

**Comment by Wholloran** [comment]
The error is no longer displaying after leaving and going back to the screen, closing ticket
