### ISSUE TITLE
Settings: Missing '+" Next to New connection

### ISSUE THREAD

**Issue by Wholloran** [openforge/junto-scope#66]
While on the settings page there is is no "+" next to "New connection". Attached is a screenshot of the current look and the marvel
![screen shot 2018-08-07 at 11 17 56 am](https://user-images.githubusercontent.com/37937571/43791722-98317368-9a44-11e8-8d8f-70fcd4d028e9.png)
![screen shot 2018-08-07 at 1 20 18 pm](https://user-images.githubusercontent.com/37937571/43791748-ad3c5f0c-9a44-11e8-8795-67de0a7c55cd.png)

v1.0.0 Emulated on Pixel 2 on Chrome

**Comment by PaulPaulDevelops** [comment]
This was resolved in the `connection-list` component. I copied the styles over and directly committed to `feature/ionic-3`. Please pull branch and re-review issue @Wholloran

**Comment by Wholloran** [comment]
"+" is now there, Closing ticket
