### ISSUE TITLE
DashBoard: There is a back button showing on the Dashboard

### ISSUE THREAD

**Issue by Wholloran** [openforge/junto-scope#67]
There is a back button showing on the Dashboard if pressed it will take you back to the Login screen.
![screen shot 2018-08-07 at 2 59 28 pm](https://user-images.githubusercontent.com/37937571/43796523-80fa4914-9a52-11e8-9328-d74b845c6963.png)

v1.0.0 Present on iOS and Android emulated and native

**Comment by PaulPaulDevelops** [comment]
I added extra logic as recommended by Ionic to not show the back button on this page. I'm not sure if this is what we want entirely, as it will not show the back button in any scenario or flow on this page anymore ... but we can adjust it if necessary. 

I committed this change directly to `feature/ionic-3`. Could you please re-test and update the issue if necessary? @Wholloran

**Comment by Wholloran** [comment]
I'm no longer seeing a back button on the dashboard closing the ticket
