### ISSUE TITLE
DashBoard: The "M" and "P" are displaying to the left

### ISSUE THREAD

**Issue by Wholloran** [openforge/junto-scope#68]
On the DashBoard The "M" and "P" are displaying to the left, they should be on the right side per Marvel.

![screen shot 2018-08-07 at 3 01 35 pm](https://user-images.githubusercontent.com/37937571/43796636-ce903256-9a52-11e8-8039-84a4abd47c4d.png)

v1.0.0 Present on all devices Emulated and Native

**Comment by PaulPaulDevelops** [comment]
I noticed that the ID (which should be the project name) is not the primary orange color, so I will update this as well.

**Comment by PaulPaulDevelops** [comment]
I updated the button to float to the right and to be in-line with the project title (it's the ID for right now).
I pushed directly into `feature/ionic-3` if you can re-test and update the issue @Wholloran

**Comment by Wholloran** [comment]
Icons are displaying to the Right, Closing ticket
