### ISSUE TITLE
New Connection: - Clicking the “where do I Find this” link in the create a connection flow doesn’t direct anywhere

### ISSUE THREAD

**Issue by Wholloran** [openforge/junto-scope#70]
Clicking the “where do I Find this” link in the create a connection flow doesn’t direct anywhere, It will also Log you out of the application

Steps to recreate:
1. Log in to Juntoscope
2. Click new connection
3. Click teamwork
4. Click "Where do I find this"

v1.0.0

**Comment by daftclaud** [comment]
Someone, please close this after review. It was a one-liner

**Comment by Fdom92** [comment]
I review this on feature/ionic-3 branch and works, it redirects to where to find the key.

Closing this.
