### ISSUE TITLE
Creating a Scoping Session: No way back on Start Scoping Session Page

### ISSUE THREAD

**Issue by Wholloran** [openforge/junto-scope#74]
On the Start a Scoping session page there is no way back on the  Start Scoping Session page. no back button or header to navigate to the dashboard

Steps to reproduce:
1. Login to account with active connections
2. Click on a connection
3. Select project
4. Select tasks

 Please see attached screenshots and Marvel link: https://marvelapp.com/337ic5h/screen/46275362
![screen shot 2018-08-07 at 5 34 58 pm](https://user-images.githubusercontent.com/37937571/43804072-c69b5ff6-9a68-11e8-90b3-6c56e3e4877c.png)

**Comment by PaulPaulDevelops** [comment]
@Wholloran I can add a back button in for this page. Should the back button go into the dashboard? As this is the end of this specific flow.

**Comment by Fdom92** [comment]
@PaulPaulDevelops @Wholloran this is cause the share link is a modal so thats why even with nav bar there is no back button. I fixed this changing the nav bar (cause on modals is not needed) into a toolbar and adding a button at start to go to dashboard. I'm going to create a PR with the fix.

**Comment by Wholloran** [comment]
You can now go back from this page, Closing Ticket
