### ISSUE TITLE
Lock Device Orientation

### ISSUE THREAD

**Issue by PaulPaulDevelops** [openforge/junto-scope#75]
We should set and lock the device orientation in order for the app always be in portrait mode. We do not have designs for landscape at the moment, nor is the frontend optimized for this.

On XCode, we can set this, but as for Android, I believe we have to look into a solution. With a brief Google search, I found[ a plugin ](https://ionicframework.com/docs/native/screen-orientation/) that seems to do the trick.

**Comment by Wholloran** [comment]
Device orientation is locked on both Android and Apple, Closing ticket
