### ISSUE TITLE
Scoping as a moderator: No way back to dashboard

### ISSUE THREAD

**Issue by Wholloran** [openforge/junto-scope#77]
There is no JuntoScope header on the sessions result screen to take you back to the dashboard, so you can not get back to the dashboard.

Please see screenshot of current page and Marvel URL of expected: https://marvelapp.com/337ic5h/screen/46275361
<img width="207" alt="screen shot 2018-08-07 at 7 06 00 pm" src="https://user-images.githubusercontent.com/37937571/43807140-15d5747e-9a75-11e8-91c3-e264db58acde.png">

**Comment by Wholloran** [comment]
So The issue with adding the settings button here is that we still have the same issue. You can click to go to the settings now but if you go back you are taken to the "final results" page still. Therefore there is no way to get to the home page.

A solution here would be to add the JuntoScope header that leads to the dashboard when clicked, or just change the back button in this state to "<- Home" and have it navigate to the Dashboard

Also this is a case of what I believe is called "inconsistent element" (its from a UI/UX desk i use to have to test good UI) having the settings thereafter the user being used to it on the right give it a bad flow feel

@PaulPaulDevelops @Fdom92

**Comment by Fdom92** [comment]
@Wholloran @PaulPaulDevelops we should then just show the back button to go to dashboard or the back button and settings button?

**Comment by Wholloran** [comment]
There is now a back button that takes you to the dashboard, Closing ticket
