### ISSUE TITLE
DashBoard: Numbers are being displayed instead of project title

### ISSUE THREAD

**Issue by Wholloran** [openforge/junto-scope#81]
Numbers are being displayed instead of the project title on the history section of the dashboard, Paulina said this is because we are currently not receiving that information so making a task to get this information.

<img width="196" alt="screen shot 2018-08-07 at 7 26 25 pm" src="https://user-images.githubusercontent.com/37937571/43807732-d3c2abd0-9a77-11e8-8ea9-19be10d082b5.png">

**Comment by PaulPaulDevelops** [comment]
This has been resolved in pull request #63. Please re-review and test.

**Comment by Wholloran** [comment]
Project title is now beign displayed on both Android and iOS, closing ticket
