### ISSUE TITLE
Authentication: Unable to log in on Android

### ISSUE THREAD

**Issue by Wholloran** [openforge/junto-scope#82]
- On Android I am being Prompted natively with google to login but after selecting the account nothing is happening (It doesn’t look like the process of authentication and being pushed dot the dashboard is working correctly

Steps to recreate:
1. Launch on an android device
2. check terms
3. click google login
4. click the account you want to log in with
5. Nothing happens

**Comment by Fdom92** [comment]
Hi @Wholloran i just tried to reproduce this one and for me the app redirects to the dashboard page.

Tried this on android

**Comment by daftclaud** [comment]
Just confirmed this issue. We are getting error code 10.

https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/503

**Comment by PaulPaulDevelops** [comment]
Closing this and opening up new issue ticket(s)
