### ISSUE TITLE
Add a connection: Unable to add a connection

### ISSUE THREAD

**Issue by Wholloran** [openforge/junto-scope#83]
On iOS and Android devices you are unable to add an API key. HWne entering a valid API key and pressing enter nothing happens

Steps to recreate:
1. log in
2.Click ass a connection
3. click teamwork
4. enter correct API key and hit enter

v1.0.0 Google pixel, Sony xpria, iPhoneX

**Comment by Fdom92** [comment]
@Wholloran this is cause we are using the functions in local, so when we run it on the device, we don't have the functions running on local.

We should discuss this and maybe start using the dev env on firebase for the function instead of localhost @PaulPaulDevelops @daftclaud

**Comment by daftclaud** [comment]
I don't see an issue with deploying the functions on the dev environment before testing. The command is 'firebase serve --only functions'

**Comment by PaulPaulDevelops** [comment]
I deployed the updates of the functions to the dev URL and built pointing to that environment. The issue should now be resolved.

**Comment by Wholloran** [comment]
Able to add a connection on both ANdroid or iOS, closing Ticket
