### ISSUE TITLE
Scope Session Flow Transition for Moderator and Participant

### ISSUE THREAD

**Issue by Wholloran** [openforge/junto-scope#91]
Review the transition of each flow throughout the scoping session for both the moderator and participant. The looping that is currently not structured / consistent with what is expected for this flow. Outlined is the expected flow for each user type :

**Moderator:**
1. Scopes individual task. Waiting for participants to complete entering scopes prior to moving to the next screen.
3. Selects final scope for the task.
4. Result screen for that instance
5a. If there are tasks left in the scope session it should transition back to #1.
5b. If there are no tasks left in the scope session it should transition to show final session details page.

**Participant:**
1. Selects scope for the individual task. Waits for participants to complete entering in scopes. Then is waiting for the moderator to select the final scope for that task. Once both are complete it will transition to the next screen.
2. Shows the result screen for that specific task.
3a. If there are tasks left in the scope session it should transition back to #1.
3b If there are no tasks left in the scope session it should transition to show final session details page.

**Comment by daftclaud** [comment]
Caveat: The scoping flow breaks with subtasks. Perhaps it would be better to add a dropdown for task-lists with sub-task-lists and select the sub-task-lists.

**Comment by daftclaud** [comment]
As per our meeting today, I will integrate subtasks as if they were regular tasks. Updating my branch now. PR Soon.

**Comment by Wholloran** [comment]
The flow follows the above listing so closing the ticket
